= Extreme Connect 4

== Question

=== Background

Extreme Connect 4 is a variant of Connect 4 in which:

* The rows and columns are infinite
    ** Rows have range: `[0, infinity)`
    ** Columns have range: `[-infinity, infinity]`
* Players place chips at the **bottom** of the stack and push all chips above it up 1 row
* Players take turns placing chips; the first player to get four consecutive chips in a row or column wins (diagonals do not matter)

=== Task

Implement a function that takes in a player and column index and returns the winner (if there is one).

== Explanation

=== Modeling the board

In a normal game of connect 4, an array is a good option since the board is a fixed structure with constant-time retrievals.
This board is infinite though, so allocating an 2-D array of maximum size is a huge waste of space.
We need something more dynamic that can hold chips in columns at the far-left (negative infinity) and the far-right (positive infinity).
We also need to be able to efficiently access the columns so we can insert chips in arbitrary columns.
With this in mind, a map makes sense to represent the board with keys being the indices of the columns.

What should be used for the columns?
A stack models the problem well, but we need to be able to quickly access all the elements in the structure, not just the top.
With that in mind, a re-sizable list can be used.
It gives us the functionality of the stack while allowing us to access its elements in constant time.

=== Checking for wins

Let's start with checking for column wins (vertical) since it is simpler.
Since we know what column the chip was just placed in, we only have to check that column.
We also only have to check the bottom 4 chips instead of the entire column.

Row wins are trickier. 
Since all the chips in the column move, we need to check each of those rows.
We essentially check every row that this column has a piece in.

=== Tricky Parts

Since chips are moved up, it's possible for both players to have 4 in a row/column from the same move.
We should bring this up with the interviewer and discuss how to resolve ties.
In this solution, wins in lower rows will have priority.

== Solution

.ExtremeConnectFour.java
[source,java]
----
include::src/ExtremeConnectFour.java[]
----
